INSERT INTO companies (company_name) VALUES ('EPAM');
INSERT INTO companies (company_name) VALUES ('Express Soft');
INSERT INTO companies (company_name) VALUES ('Mega soft');

INSERT INTO customers (customer_name) VALUES ('JuViTem');
INSERT INTO customers (customer_name) VALUES ('MTC');
INSERT INTO customers (customer_name) VALUES ('Life');
INSERT INTO customers (customer_name) VALUES ('Privat Bank');
INSERT INTO customers (customer_name) VALUES ('ATB');
INSERT INTO customers (customer_name) VALUES ('Metro');
INSERT INTO customers (customer_name) VALUES ('Provigo');

INSERT INTO skills (skill_name) VALUES ('Java');
INSERT INTO skills (skill_name) VALUES ('C++');
INSERT INTO skills (skill_name) VALUES ('HTML');
INSERT INTO skills (skill_name) VALUES ('CSS');
INSERT INTO skills (skill_name) VALUES ('JavaScript');
INSERT INTO skills (skill_name) VALUES ('Hibernate');
INSERT INTO skills (skill_name) VALUES ('Ruby');

INSERT INTO developers (first_name, last_name, birth_date, address, salary, company_id) VALUES ('Oleg', 'Smolovyk', '1981-01-01', 'Montreal', 5000, 1);
INSERT INTO developers (first_name, last_name, birth_date, address, salary, company_id) VALUES ('Ivan', 'Ivanov', '1978-01-01', 'Kiev', 2000, 2);
INSERT INTO developers (first_name, last_name, birth_date, address, salary, company_id) VALUES ('Petr', 'Petrov', '1999-01-01', 'Kiev', 1000, 3);
INSERT INTO developers (first_name, last_name, birth_date, address, salary, company_id) VALUES ('Sergey', 'Sidorov', '1993-01-01', 'Montreal', 2200, 1);
INSERT INTO developers (first_name, last_name, birth_date, address, salary, company_id) VALUES ('Mark', 'Vorobev', '1964-01-01', 'Montreal', 2800, 2);
INSERT INTO developers (first_name, last_name, birth_date, address, salary, company_id) VALUES ('Taras', 'Gilfanov', '1992-01-01', 'Toronto', 1300, 3);
INSERT INTO developers (first_name, last_name, birth_date, address, salary, company_id) VALUES ('Ivan', 'Dubinets', '1989-01-01', 'Toronto', 800, 1);
INSERT INTO developers (first_name, last_name, birth_date, address, salary, company_id) VALUES ('Gena', 'Pacira', '1973-01-01', 'Toronto', 500, 2);
INSERT INTO developers (first_name, last_name, birth_date, address, salary, company_id) VALUES ('Vika', 'Ivashko', '1970-01-01', 'Vancouver', 2450, 1);
INSERT INTO developers (first_name, last_name, birth_date, address, salary, company_id) VALUES ('Katya', 'Kurtyak', '1990-01-01', 'Vancouver', 4300, 1);
INSERT INTO developers (first_name, last_name, birth_date, address, salary, company_id) VALUES ('Evgeniy', 'Levitskiy', '1990-01-01', 'Vancouver', 4800, 2);
INSERT INTO developers (first_name, last_name, birth_date, address, salary, company_id) VALUES ('Gleb', 'Karpov', '1993-01-01', 'Kharkov', 3700, 3);
INSERT INTO developers (first_name, last_name, birth_date, address, salary, company_id) VALUES ('Denis', 'Karasev', '1998-01-01', 'Kharkov', 2600, 1);
INSERT INTO developers (first_name, last_name, birth_date, address, salary, company_id) VALUES ('Artem', 'Kozlov', '1985-01-01', 'Lvov', 1900, 2);
INSERT INTO developers (first_name, last_name, birth_date, address, salary, company_id) VALUES ('Egor', 'Rozman', '1985-01-01', 'Lvov', 1700, 3);
INSERT INTO developers (first_name, last_name, birth_date, address, salary, company_id) VALUES ('Pavel', 'Yakushko', '1981-01-01', 'Lvov', 1250, 1);
INSERT INTO developers (first_name, last_name, birth_date, address, salary, company_id) VALUES ('Konstantin', 'Pekar', '1987-01-01', 'Odessa', 750, 2);
INSERT INTO developers (first_name, last_name, birth_date, address, salary, company_id) VALUES ('Yaroslav', 'Pavlov', '1988-01-01', 'Odessa', 450, 1);
INSERT INTO developers (first_name, last_name, birth_date, address, salary, company_id) VALUES ('Uriy', 'Ingushko', '1989-01-01', 'Odessa', 960, 2);
INSERT INTO developers (first_name, last_name, birth_date, address, salary, company_id) VALUES ('Vladimir', 'Sidorenko', '1989-01-01', 'Montreal', 2670, 1);
INSERT INTO developers (first_name, last_name, birth_date, address, salary, company_id) VALUES ('Max', 'Poddubniy', '1981-01-01', 'Toronto', 3000, 2);

INSERT INTO developer_skills VALUES (1, 1);
INSERT INTO developer_skills VALUES (1, 3);
INSERT INTO developer_skills VALUES (1, 4);
INSERT INTO developer_skills VALUES (2, 1);
INSERT INTO developer_skills VALUES (2, 2);
INSERT INTO developer_skills VALUES (3, 7);
INSERT INTO developer_skills VALUES (4, 5);
INSERT INTO developer_skills VALUES (4, 4);
INSERT INTO developer_skills VALUES (5, 6);
INSERT INTO developer_skills VALUES (5, 1);
INSERT INTO developer_skills VALUES (6, 5);
INSERT INTO developer_skills VALUES (6, 7);
INSERT INTO developer_skills VALUES (7, 3);
INSERT INTO developer_skills VALUES (7, 4);
INSERT INTO developer_skills VALUES (8, 5);
INSERT INTO developer_skills VALUES (8, 6);
INSERT INTO developer_skills VALUES (9, 1);
INSERT INTO developer_skills VALUES (10, 1);
INSERT INTO developer_skills VALUES (10, 2);
INSERT INTO developer_skills VALUES (11, 7);
INSERT INTO developer_skills VALUES (12, 6);
INSERT INTO developer_skills VALUES (13, 5);
INSERT INTO developer_skills VALUES (14, 1);
INSERT INTO developer_skills VALUES (14, 4);
INSERT INTO developer_skills VALUES (14, 5);
INSERT INTO developer_skills VALUES (15, 2);
INSERT INTO developer_skills VALUES (16, 3);
INSERT INTO developer_skills VALUES (17, 4);
INSERT INTO developer_skills VALUES (18, 5);
INSERT INTO developer_skills VALUES (18, 6);
INSERT INTO developer_skills VALUES (19, 7);
INSERT INTO developer_skills VALUES (20, 1);
INSERT INTO developer_skills VALUES (21, 2);

INSERT INTO projects (project_name, cost, customer_id, company_id) VALUES ('Star', 1000000, 7, 1);
INSERT INTO projects (project_name, cost, customer_id, company_id) VALUES ('Wind', 800000, 6, 1);
INSERT INTO projects (project_name, cost, customer_id, company_id) VALUES ('White', 300000, 5, 1);
INSERT INTO projects (project_name, cost, customer_id, company_id) VALUES ('Black', 600000, 4, 2);
INSERT INTO projects (project_name, cost, customer_id, company_id) VALUES ('Paint', 100000, 3, 3);
INSERT INTO projects (project_name, cost, customer_id, company_id) VALUES ('Notepad', 20000, 2, 1);
INSERT INTO projects (project_name, cost, customer_id, company_id) VALUES ('Site', 450000, 1, 2);
INSERT INTO projects (project_name, cost, customer_id, company_id) VALUES ('Mobile App', 750000, 1, 3);
INSERT INTO projects (project_name, cost, customer_id, company_id) VALUES ('Rabbit', 950000, 2, 1);
INSERT INTO projects (project_name, cost, customer_id, company_id) VALUES ('Cow', 340000, 3, 2);
INSERT INTO projects (project_name, cost, customer_id, company_id) VALUES ('Winner', 250000, 1, 2);

INSERT INTO developer_projects VALUES (1, 1);
INSERT INTO developer_projects VALUES (2, 2);
INSERT INTO developer_projects VALUES (3, 3);
INSERT INTO developer_projects VALUES (4, 4);
INSERT INTO developer_projects VALUES (5, 5);
INSERT INTO developer_projects VALUES (6, 6);
INSERT INTO developer_projects VALUES (7, 7);
INSERT INTO developer_projects VALUES (8, 6);
INSERT INTO developer_projects VALUES (9, 2);
INSERT INTO developer_projects VALUES (10, 3);
INSERT INTO developer_projects VALUES (11, 4);
INSERT INTO developer_projects VALUES (12, 5);
INSERT INTO developer_projects VALUES (13, 1);
INSERT INTO developer_projects VALUES (14, 2);
INSERT INTO developer_projects VALUES (15, 3);
INSERT INTO developer_projects VALUES (16, 4);
INSERT INTO developer_projects VALUES (17, 1);
INSERT INTO developer_projects VALUES (18, 2);
INSERT INTO developer_projects VALUES (19, 3);
INSERT INTO developer_projects VALUES (20, 1);
INSERT INTO developer_projects VALUES (21, 2);


